routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [
    'as' => 'home',
    'uses' => 'HomeController@index'
]);

Route::get('/reset_password', [
    'as' => 'auth.reset_password',
    'uses' => 'Auth\ResetPasswordController@showResetForm'
]);

Route::get('/announcements', [
    'as' => 'home.announcements',
    'uses' => 'HomeController@announcements'
]);

//-----------POSTULANT CREATE--------------//
Route::get('postulans/create', [
    'as' => 'postulans.create',
    'uses' => 'PostulantController@create',
]);
Route::post('postulans/store', [
    'as' => 'postulans.store',
    'uses' => 'PostulantController@store',
]);

////////////////////// ADMIN ROUTES ///////////////////
Route::group(['prefix' => 'admin', 'middleware' => ['auth'], 'as' => 'admin.', 'namespace' => 'Admin'], function() {
    Route::get('dashboard', [
        'as' => 'dashboard',
        'uses' => 'HomeController@index'
    ]);

    //------------ USERS --------------//
    Route::get('users', [
        'as' => 'users.index',
        'uses' => 'UserController@index',
    ])->middleware('permission:list users');
    Route::get('users/create', [
        'as' => 'users.create',
        'uses' => 'UserController@create',
    ])->middleware('permission:create users');
    Route::post('users/store', [
        'as' => 'users.store',
        'uses' => 'UserController@store',
    ])->middleware('permission:create users');
    Route::get('users/{user}/edit', [
        'as' => 'users.edit',
        'uses' => 'UserController@edit',
    ])->middleware('permission:edit users');
    Route::put('users/{user}', [
        'as' => 'users.update',
        'uses' => 'UserController@update',
    ])->middleware('permission:edit users');
    Route::patch('users/{user}', [
        'as' => 'users.update',
        'uses' => 'UserController@update',
    ])->middleware('permission:edit users');
    Route::delete('users/{user}', [
        'as' => 'users.destroy',
        'uses' => 'UserController@destroy',
    ])->middleware('permission:delete users');

    //------------ ROLES --------------//
    Route::get('roles', [
        'as' => 'roles.index',
        'uses' => 'RoleController@index',
    ])->middleware('permission:list roles');
    Route::get('roles/create', [
        'as' => 'roles.create',
        'uses' => 'RoleController@create',
    ])->middleware('permission:list roles');
    Route::post('roles/store', [
        'as' => 'roles.store',
        'uses' => 'RoleController@store',
    ])->middleware('permission:list roles');
    Route::get('roles/{role}/edit', [
        'as' => 'roles.edit',
        'uses' => 'RoleController@edit',
    ])->middleware('permission:list roles');
    Route::put('roles/{role}', [
        'as' => 'roles.update',
        'uses' => 'RoleController@update',
    ])->middleware('permission:list roles');
    Route::patch('roles/{role}', [
        'as' => 'roles.update',
        'uses' => 'RoleController@update',
    ])->middleware('permission:list roles');
    Route::delete('roles/{role}', [
        'as' => 'roles.destroy',
        'uses' => 'RoleController@destroy',
    ])->middleware('permission:list roles');

    //------------ announcements --------------//
    Route::get('announcements', [
        'as' => 'announcements.index',
        'uses' => 'AnnouncementController@index',
    ])->middleware('permission:list announcements');
    Route::get('announcements/{announcement}/show', [
        'as' => 'announcements.show',
        'uses' => 'AnnouncementController@show',
    ]);
    Route::post('announcements/{announcement}/compare', [
        'as' => 'announcements.compare',
        'uses' => 'AnnouncementController@compare',
    ]);
    Route::get('announcements/create', [
        'as' => 'announcements.create',
        'uses' => 'AnnouncementController@create',
    ])->middleware('permission:create announcements');
    Route::post('announcements/store', [
        'as' => 'announcements.store',
        'uses' => 'AnnouncementController@store',
    ])->middleware('permission:create announcements');
    Route::get('announcements/{announcement}/edit', [
        'as' => 'announcements.edit',
        'uses' => 'AnnouncementController@edit',
    ])->middleware('permission:edit announcements');
    Route::put('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');
    Route::put('announcements/{announcement}/update_code', [
        'as' => 'announcements.code',
        'uses' => 'AnnouncementController@updateCode',
    ]);
    Route::patch('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');

    Route::get('announcements/{announcement}/files', [
        'as' => 'requirements.files',
        'uses' => 'AnnouncementController@requirement',
    ]);

    Route::delete('announcements/{announcement}', [
        'as' => 'announcements.destroy',
        'uses' => 'AnnouncementController@destroy',
    ])->middleware('permission:delete announcements');

    //------------ Postulants --------------//
    Route::get('{announcement}/postulants', [
        'as' => 'postulants.index',
        'uses' => 'PostulantController@index',
    ])->middleware('permission:list postulants');
    Route::get('announcements/{announcement}/postulants/{postulant}/files', [
        'as' => 'postulants.show',
        'uses' => 'PostulantController@show',
    ]);
    Route::get('{announcement}/postulants/create', [
        'as' => 'postulants.create',
        'uses' => 'PostulantController@create',
    ])->middleware('permission:create postulants');
    Route::get('{announcement}/postulants/{postulant}/requirement/{requirement}/checked', [
        'as' => 'postulants.checkedFile',
        'uses' => 'PostulantController@checked',
    ]);
    Route::post('{announcement}/postulants/store', [
        'as' => 'postulants.store',
        'uses' => 'PostulantController@store',
    ])->middleware('permission:create postulants');
    Route::get('{announcement}/postulants/{postulant}/edit', [
        'as' => 'postulants.edit',
        'uses' => 'PostulantController@edit',
    ])->middleware('permission:edit postulants');
    Route::put('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.update',
        'uses' => 'PostulantController@update',
    ])->middleware('permission:edit postulants');
    Route::patch('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.update',
        'uses' => 'PostulantController@update',
    ])->middleware('permission:edit postulants');
    Route::delete('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.destroy',
        'uses' => 'PostulantController@destroy',
    ])->middleware('permission:delete postulants');

    //-------------- AREAS ------------------//
    Route::get('areas', [
        'as' => 'areas.index',
        'uses' => 'AreaController@index',
    ])->middleware('permission:list areas');
    Route::get('areas/create', [
        'as' => 'areas.create',
        'uses' => 'AreaController@create',
    ])->middleware('permission:create areas');
    Route::post('areas/store', [
        'as' => 'areas.store',
        'uses' => 'AreaController@store',
    ])->middleware('permission:create areas');
    Route::get('areas/{area}/edit', [
        'as' => 'areas.edit',
        'uses' => 'AreaController@edit',
    ])->middleware('permission:edit areas');
    Route::put('areas/{area}', [
        'as' => 'areas.update',
        'uses' => 'AreaController@update',
    ])->middleware('permission:edit areas');
    Route::patch('areas/{area}', [
        'as' => 'areas.update',
        'uses' => 'AreaController@update',
    ])->middleware('permission:edit areas');
    Route::delete('areas/{area}', [
        'as' => 'areas.destroy',
        'uses' => 'AreaController@destroy',
    ])->middleware('permission:delete areas');

    //-------------- CONVOCATORIAS ------------------//
    Route::get('announcements', [
        'as' => 'announcements.index',
        'uses' => 'AnnouncementController@index',
    ])->middleware('permission:list announcements');
    Route::get('announcements/create', [
        'as' => 'announcements.create',
        'uses' => 'AnnouncementController@create',
    ])->middleware('permission:create announcements');
    Route::post('announcements/store', [
        'as' => 'announcements.store',
        'uses' => 'AnnouncementController@store',
    ])->middleware('permission:create announcements');
    Route::get('announcements/{id}/edit', [
        'as' => 'announcements.edit',
        'uses' => 'AnnouncementController@edit',
    ])->middleware('permission:edit announcements');
    Route::put('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');
    Route::patch('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');
    Route::delete('announcements/{announcement}', [
        'as' => 'announcements.destroy',
        'uses' => 'AnnouncementController@destroy',
    ])->middleware('permission:delete announcements');

    //-------------- REQUIREMENTS ------------------//
    Route::get('{announcement}/requirements', [
        'as' => 'requirements.index',
        'uses' => 'RequirementController@index',

app/Http/Controllers/Admin/PostulantController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Announcement;
use App\File;
use App\Requirement;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class PostulantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Announcement $announcement)
    {
        $postulants = $announcement->postulants;

        return View('admin.postulants.index', [ 'announcement' => $announcement, 'postulants' => $postulants ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Announcement $announcement, User $postulant)
    {
        return View('admin.postulants.show', [ 'announcement' => $announcement, 'postulant' => $postulant ]);
    }

    /**
     * Checked file requirement.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function checked(Announcement $announcement, User $postulant, Requirement $requirement)
    {
        $file = File::where('user_id', $postulant->id)
            ->where('requirement_id', $requirement->id)->first();

        if (!isset($file))
            return response()->json(['code' => 404, 'message' => 'no existe el registro']);

        if ($file->checked)
            $file->checked = 0;
        else
            $file->checked = 1;

        $file->save();

        return response()->json(['code' => 200, 'message' => 'Archivo Validado', 'data' => $file]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PostulantController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostulantRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\View\View;

class PostulantController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('postulant_register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostulantRequest $request)
    {
        $postulant = new User($request->all());
        $postulant->password = (bcrypt($postulant->password));
        $postulant->save();

        $postulant->syncRoles(['Postulante']);
        // $postulant->assignRole(['Postulante']);

        return redirect(route('login'))->with([ 'message' => 'Usuario creado exitosamente!', 'alert-type' => 'success' ]);
    }

}

resources/views/admin/postulants/index.blade.php
@extends('admin.layouts.app')

@section('htmlheader_title')
   Postulants
@endsection


@section('content')
    <div class="card">
        <div class="card-header">
            <i class="fa fa-align-justify"></i> Postulantes
            @can('create postulants')
                <a class="btn btn-secondary" href="{{ route('admin.users.create') }}">
                    <i class="icon-plus"></i>&nbsp;Nuevo
                </a>
            @endcan
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped table-sm">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Telefono</th>
                    <th>Email</th>
                    <th>Opciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($postulants as $postulant)
                    <tr>
                        <td>{{ $postulant->name }}</td>
                        <td>{{ $postulant->lastname }}</td>
                        <td>{{ $postulant->phone }}</td>
                        <td>{{ $postulant->email }}</td>
                        <td>

                            <a class="btn btn-warning btn-sm" href="{{ route('admin.postulants.show', ['announcement' => $announcement->id, 'postulant' =>$postulant->id]) }}">
                                <i class="icon-pencil"></i>Revisar
                            </a>

                            <form action="{{ route('admin.postulants.destroy', ['announcement' =>$announcement->id, 'postulant' =>$postulant->id]) }}"
                                  style="display:inline-block;"
                                  method="POST">

                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <button type="button" class="btn btn-danger btn-sm"
                                        onclick="delete_action(event);">
                                    <i class="icon-trash"></i>Eliminar
                                </button>
                            </form>

                        </td>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/postulants/show.blade.php
@extends('admin.layouts.app')

@section('htmlheader_title')
    Requirements
@endsection

@section('content')
    <div class="card" style="height: 100vh">
        <div class="card-header text-center title-panel">Archivos - {{ $postulant->name . ' ' . $postulant->lastname }}</div>
        <div class="card-body" style="background-image: url('{{ asset('images/adinfondo.jpg') }}'); background-size: cover; background-repeat: no-repeat">
            <div class="row">
                <div class="col-3">
                    <div class="card border-info shadow_card special-card">
                        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                            <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">REQUISITOS INDISPENSABLES</a>
                            <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">REQUISITOS GENERALES</a>
                            <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">CONSULTAS</a>
                        </div>
                    </div>
                </div>
                <div class="col-9">
                    <div class="card">
                        <div class="tab-content" id="v-pills-tabContent">
                            <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                                @include('admin.postulants.partials.list', [ 'postulant' => $postulant, 'items' => $announcement->requiredRequirements() ])
                            </div>
                            <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                                @include('admin.postulants.partials.list', [ 'postulant' => $postulant, 'items' => $announcement->generalRequirements() ])
                            </div>
                            <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                                CHAT
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        const checkedFile = (announcement_id, user_id, requirement_id) => {
            var url = '{{ route("admin.postulants.checkedFile", [ "announcement" => ":announcement_id", "postulant" => ":user_id", "requirement" => ":requirement_id" ] ) }}'

            url = url.replace(':user_id', user_id)
            url = url.replace(':requirement_id', requirement_id)
            url = url.replace(':announcement_id', announcement_id)

            fetch(url, {
                method: 'GET',
                //body: new URLSearchParams({code: text}),
                headers: new Headers({
                    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }),
            }).then(async response => {
                if (!response.ok) {
                    throw new Error(response.statusText)
                }

                let res = await response.json()

                if (res.code == 200)
                    toastr.success(res.message)
            })


        }
    </script>
@endsection