routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [
    'as' => 'home',
    'uses' => 'HomeController@index'
]);

Route::get('/reset_password', [
    'as' => 'auth.reset_password',
    'uses' => 'Auth\ResetPasswordController@showResetForm'
]);

Route::get('/announcements', [
    'as' => 'home.announcements',
    'uses' => 'HomeController@announcements'
]);

//-----------POSTULANT CREATE--------------//
Route::get('postulans/create', [
    'as' => 'postulans.create',
    'uses' => 'PostulantController@create',
]);
Route::post('postulans/store', [
    'as' => 'postulans.store',
    'uses' => 'PostulantController@store',
]);

////////////////////// ADMIN ROUTES ///////////////////
Route::group(['prefix' => 'admin', 'middleware' => ['auth'], 'as' => 'admin.', 'namespace' => 'Admin'], function() {
    Route::get('dashboard', [
        'as' => 'dashboard',
        'uses' => 'HomeController@index'
    ]);

    //------------ USERS --------------//
    Route::get('users', [
        'as' => 'users.index',
        'uses' => 'UserController@index',
    ])->middleware('permission:list users');
    Route::get('users/create', [
        'as' => 'users.create',
        'uses' => 'UserController@create',
    ])->middleware('permission:create users');
    Route::post('users/store', [
        'as' => 'users.store',
        'uses' => 'UserController@store',
    ])->middleware('permission:create users');
    Route::get('users/{user}/edit', [
        'as' => 'users.edit',
        'uses' => 'UserController@edit',
    ])->middleware('permission:edit users');
    Route::put('users/{user}', [
        'as' => 'users.update',
        'uses' => 'UserController@update',
    ])->middleware('permission:edit users');
    Route::patch('users/{user}', [
        'as' => 'users.update',
        'uses' => 'UserController@update',
    ])->middleware('permission:edit users');
    Route::delete('users/{user}', [
        'as' => 'users.destroy',
        'uses' => 'UserController@destroy',
    ])->middleware('permission:delete users');

    //------------ ROLES --------------//
    Route::get('roles', [
        'as' => 'roles.index',
        'uses' => 'RoleController@index',
    ])->middleware('permission:list roles');
    Route::get('roles/create', [
        'as' => 'roles.create',
        'uses' => 'RoleController@create',
    ])->middleware('permission:list roles');
    Route::post('roles/store', [
        'as' => 'roles.store',
        'uses' => 'RoleController@store',
    ])->middleware('permission:list roles');
    Route::get('roles/{role}/edit', [
        'as' => 'roles.edit',
        'uses' => 'RoleController@edit',
    ])->middleware('permission:list roles');
    Route::put('roles/{role}', [
        'as' => 'roles.update',
        'uses' => 'RoleController@update',
    ])->middleware('permission:list roles');
    Route::patch('roles/{role}', [
        'as' => 'roles.update',
        'uses' => 'RoleController@update',
    ])->middleware('permission:list roles');
    Route::delete('roles/{role}', [
        'as' => 'roles.destroy',
        'uses' => 'RoleController@destroy',
    ])->middleware('permission:list roles');

    //------------ announcements --------------//
    Route::get('announcements', [
        'as' => 'announcements.index',
        'uses' => 'AnnouncementController@index',
    ])->middleware('permission:list announcements');
    Route::get('announcements/{announcement}/show', [
        'as' => 'announcements.show',
        'uses' => 'AnnouncementController@show',
    ]);
    Route::post('announcements/{announcement}/compare', [
        'as' => 'announcements.compare',
        'uses' => 'AnnouncementController@compare',
    ]);
    Route::get('announcements/create', [
        'as' => 'announcements.create',
        'uses' => 'AnnouncementController@create',
    ])->middleware('permission:create announcements');
    Route::post('announcements/store', [
        'as' => 'announcements.store',
        'uses' => 'AnnouncementController@store',
    ])->middleware('permission:create announcements');
    Route::get('announcements/{announcement}/edit', [
        'as' => 'announcements.edit',
        'uses' => 'AnnouncementController@edit',
    ])->middleware('permission:edit announcements');
    Route::put('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');
    Route::put('announcements/{announcement}/update_code', [
        'as' => 'announcements.code',
        'uses' => 'AnnouncementController@updateCode',
    ]);
    Route::patch('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');

    Route::get('announcements/{announcement}/files', [
        'as' => 'requirements.files',
        'uses' => 'AnnouncementController@requirement',
    ]);

    Route::delete('announcements/{announcement}', [
        'as' => 'announcements.destroy',
        'uses' => 'AnnouncementController@destroy',
    ])->middleware('permission:delete announcements');

    //------------ Postulants --------------//
    Route::get('{announcement}/postulants', [
        'as' => 'postulants.index',
        'uses' => 'PostulantController@index',
    ])->middleware('permission:list postulants');
    Route::get('announcements/{announcement}/postulants/{postulant}/files', [
        'as' => 'postulants.show',
        'uses' => 'PostulantController@show',
    ]);
    Route::get('{announcement}/postulants/create', [
        'as' => 'postulants.create',
        'uses' => 'PostulantController@create',
    ])->middleware('permission:create postulants');
    Route::get('{announcement}/postulants/{postulant}/requirement/{requirement}/checked', [
        'as' => 'postulants.checkedFile',
        'uses' => 'PostulantController@checked',
    ]);
    Route::post('{announcement}/postulants/store', [
        'as' => 'postulants.store',
        'uses' => 'PostulantController@store',
    ])->middleware('permission:create postulants');
    Route::get('{announcement}/postulants/{postulant}/edit', [
        'as' => 'postulants.edit',
        'uses' => 'PostulantController@edit',
    ])->middleware('permission:edit postulants');
    Route::put('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.update',
        'uses' => 'PostulantController@update',
    ])->middleware('permission:edit postulants');
    Route::patch('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.update',
        'uses' => 'PostulantController@update',
    ])->middleware('permission:edit postulants');
    Route::delete('{announcement}/postulants/{postulant}', [
        'as' => 'postulants.destroy',
        'uses' => 'PostulantController@destroy',
    ])->middleware('permission:delete postulants');

    //-------------- AREAS ------------------//
    Route::get('areas', [
        'as' => 'areas.index',
        'uses' => 'AreaController@index',
    ])->middleware('permission:list areas');
    Route::get('areas/create', [
        'as' => 'areas.create',
        'uses' => 'AreaController@create',
    ])->middleware('permission:create areas');
    Route::post('areas/store', [
        'as' => 'areas.store',
        'uses' => 'AreaController@store',
    ])->middleware('permission:create areas');
    Route::get('areas/{area}/edit', [
        'as' => 'areas.edit',
        'uses' => 'AreaController@edit',
    ])->middleware('permission:edit areas');
    Route::put('areas/{area}', [
        'as' => 'areas.update',
        'uses' => 'AreaController@update',
    ])->middleware('permission:edit areas');
    Route::patch('areas/{area}', [
        'as' => 'areas.update',
        'uses' => 'AreaController@update',
    ])->middleware('permission:edit areas');
    Route::delete('areas/{area}', [
        'as' => 'areas.destroy',
        'uses' => 'AreaController@destroy',
    ])->middleware('permission:delete areas');

    //-------------- CONVOCATORIAS ------------------//
    Route::get('announcements', [
        'as' => 'announcements.index',
        'uses' => 'AnnouncementController@index',
    ])->middleware('permission:list announcements');
    Route::get('announcements/create', [
        'as' => 'announcements.create',
        'uses' => 'AnnouncementController@create',
    ])->middleware('permission:create announcements');
    Route::post('announcements/store', [
        'as' => 'announcements.store',
        'uses' => 'AnnouncementController@store',
    ])->middleware('permission:create announcements');
    Route::get('announcements/{id}/edit', [
        'as' => 'announcements.edit',
        'uses' => 'AnnouncementController@edit',
    ])->middleware('permission:edit announcements');
    Route::put('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');
    Route::patch('announcements/{announcement}', [
        'as' => 'announcements.update',
        'uses' => 'AnnouncementController@update',
    ])->middleware('permission:edit announcements');
    Route::delete('announcements/{announcement}', [
        'as' => 'announcements.destroy',
        'uses' => 'AnnouncementController@destroy',
    ])->middleware('permission:delete announcements');

    //-------------- REQUIREMENTS ------------------//
    Route::get('{announcement}/requirements', [
        'as' => 'requirements.index',
        'uses' => 'RequirementController@index',

app/Announcement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Announcement extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'code',
        'start_date_announcement',
        'end_date_announcement',
        'start_date_calification',
        'end_date_calification',
    ];

    /**
     * Get the comments for the blog post.
     */
    public function areas()
    {
        return $this->belongsToMany('App\Area');
    }

    /**
     * Get the requirements for the announcement.
     */
    public function requirements()
    {
        return $this->hasMany('App\Requirement');
    }

    /**
     * Get the requirements required.
     */
    public function requiredRequirements()
    {
        $announcement = $this;

        return Requirement::where('announcement_id', $announcement->id)->where('required', 1)->get();
    }

    /**
     * Get the requirements general.
     */
    public function generalRequirements()
    {
        $announcement = $this;

        return Requirement::where('announcement_id', $announcement->id)->where('required', 0)->get();
    }

    /**
     * The users that belong to the announcement.
     */
    public function postulants()
    {
        return $this->belongsToMany('App\User');
    }

}

app/Http/Controllers/Admin/AnnouncementController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Announcement;
use App\Area;
use App\Http\Requests\AnnouncementRequest;
use Carbon\Carbon;
use Cassandra\Date;
use http\Client\Response;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\View\View;

class AnnouncementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $user = Auth::user();

        $announcements = $user->announcements;

        if ($user->hasRole(['Admin', 'Calificador']))
            $announcements = Announcement::all();

        return view('admin.announcements.index', [ 'announcements' => $announcements ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $areas = Area::all();

        $announcements = DB::table('areas')->get();
        if ($announcements->isEmpty())
            return redirect(route('admin.areas.index'))->with([ 'message' => 'Para crear convocatoria debe tener areas disponibles!', 'alert-type' => 'info' ]);

        return view('admin.announcements.create', [ 'areas' => $areas]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AnnouncementRequest $request)
    {
        $announcements = DB::table('areas')->get();
        if ($announcements->isEmpty())
            return redirect(route('admin.areas.index'))->with([ 'message' => 'Para crear convocatoria debe tener areas disponibles!', 'alert-type' => 'info' ]);


        $announcement = new Announcement($request->all());
        $announcement->start_date_announcement = new Carbon($request->start_date_announcement);
        $announcement->end_date_announcement = new Carbon($request->end_date_announcement);
        $announcement->start_date_calification = new Carbon($request->start_date_calification);
        $announcement->end_date_calification = new Carbon($request->end_date_calification);
        $announcement->code = Str::random(6);

        $announcement->save();

        $areas = Area::find($request->areas);

        $announcement->areas()->attach($areas);

        return redirect(route('admin.announcements.index'))->with([ 'message' => 'Convocatoria creado exitosamente!', 'alert-type' => 'success' ]);
    }

    /**
     * Display the specified code.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Announcement $announcement)
    {
        return response()->json($announcement);
    }

    /**
     * Compare the specified code.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function compare(Request $request, Announcement $announcement)
    {
        if (!$request->code || !$announcement->exists()){
            return response()->json([ 'message' => 'Error de datos enviados' ]);
            //return redirect(route('home.announcements'))->with([ 'message' => 'Error!', 'alert-type' => 'info' ]);
        }

        if ($request->code != $announcement->code) {
            return response()->json([ 'error' => 'El codigo no coincide', 'code' => 400 ]);
            //return redirect(route('home.announcements'))->with([ 'message' => 'Codigo incorrecto!', 'alert-type' => 'info' ]);
        }

        $user = Auth::user();

        $announcement->postulants()->attach($user);

        return response()->json([ 'code' => 200, 'announcement' => $announcement]);

        //return redirect(route('admin.announcements.index'))->with([ 'message' => 'Bienvenido a esta convocatoria!', 'alert-type' => 'info' ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $announcement = Announcement::find($id);

        $areas = Area::all();

        return view('admin.announcements.edit', [ 'announcement' => $announcement ,'areas' => $areas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AnnouncementRequest $request, $id)
    {
        $announcement = Announcement::find($id);

        $announcement->update($request->all());
        $announcement->save();

        $announcement->areas()->detach();

        $areas = Area::find($request->areas);

        $announcement->areas()->attach($areas);

        return redirect(route('admin.announcements.index'))->with([ 'message' => 'Convocatoria actualizado exitosamente!', 'alert-type' => 'info' ]);
    }

    /**
     * Update the specified code in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updateCode(Request $request, Announcement $announcement)
    {
        $announcement->code = $request->code;
        $announcement->save();

        return response()->json($announcement);
    }

    /**
     * view the specified requirements in announcement.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function requirement(Announcement $announcement)
    {
        return view('admin.announcements.requirements.requirement_postulant',
            [ 'announcement' => $announcement ]
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/announcements/create.blade.php
@extends('admin.layouts.app')

@section('htmlheader_title')
    Convocatoria
@endsection

@section('styles')
    <link href="{{ asset('assets/css/font-awesome-4.6.1/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/util.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/animate.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-edit"></i>Crear convocatoria</div>
                    <div class="card-body">
                        <form class="form-horizontal" action="{{ route('admin.announcements.store') }}" method="POST">
                            {{ csrf_field() }}

                            @include('admin.announcements.form')

                            <div class="form-actions text-center">
                                <button class="btn btn-outline-primary" type="submit">Guardar</button>
                                <a class="btn btn-outline-danger" href="{{ route('admin.announcements.index') }}">Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.col-->
        </div>
        <!-- /.row-->
    </div>

@endsection


@section('scripts')
    <script src="{{ asset('assets/js/plugins/select2/select2.js') }}"></script>
    {{--<script src="{{ asset('assets/js/plugins/ckeditor/ckeditor.js')  }}"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>--}}
    <script>
        (function () {
            const root = document.querySelector('.ex-inputs');
            const rootC = document.querySelector('.ex-inputs-calification');
            const txtDurationStart = document.querySelector('.ex-inputs-start');
            const txtDurationEnd = document.querySelector('.ex-inputs-end');
            const txtCalificationStart = document.querySelector('.ex-inputs-calification-start');
            const txtCalificationEnd = document.querySelector('.ex-inputs-calification-end');
            const containerDuration = document.querySelector('.ex-inputs-picker');
            const containerCalification = document.querySelector('.ex-inputs-calification-picker');

            let options = {
                lang: {
                    months: [
                        'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
                    ]
                }
            }

            const openPicker = (container, txtStart, txtEnd) => {
                // Inject DateRangePicker into our container
                DateRangePicker.DateRangePicker(container, {
                    startOpts: options
                })
                    .on('statechange', function (_, picker) {
                        // Update the inputs when the state changes
                        var range = picker.state;
                        txtStart.value = range.start ? range.start.toDateString() : '';
                        txtEnd.value = range.end ? range.end.toDateString() : '';
                    });
            }

            openPicker(containerDuration, txtDurationStart, txtDurationEnd)
            openPicker(containerCalification, txtCalificationStart, txtCalificationEnd)

            // When the inputs gain focus, show the date range picker
            txtDurationStart.addEventListener('focus', showDurationPicker);
            txtDurationEnd.addEventListener('focus', showDurationPicker);
            txtCalificationStart.addEventListener('focus', showCalificationPicker);
            txtCalificationEnd.addEventListener('focus', showCalificationPicker);

            function showDurationPicker() {
                containerDuration.classList.add('ex-inputs-picker-visible');
            }

            function showCalificationPicker() {
                containerCalification.classList.add('ex-inputs-picker-visible');
            }

            const closePicker = (rootContainer, container) => {
                // If focus leaves the root element, it is not in the date
                // picker or the inputs, so we should hide the date picker
                // we do this in a setTimeout because redraws cause temporary
                // loss of focus.
                let previousTimeout;
                rootContainer.addEventListener('focusout', function hidePicker() {
                    clearTimeout(previousTimeout);
                    previousTimeout = setTimeout(function() {
                        if (!rootContainer.contains(document.activeElement)) {
                            container.classList.remove('ex-inputs-picker-visible');
                        }
                    }, 10);
                });
            }

            closePicker(root, containerDuration)
            closePicker(rootC, containerCalification)


            $('.js-example-basic-multiple').select2({
                placeholder: "Seleccione un valor",
                allowClear: true
            });

        }());
    </script>
@endsection

resources/views/admin/announcements/index.blade.php
@extends('admin.layouts.app')

@section('htmlheader_title')
   Announcements
@endsection


@section('content')

    <div class="card">
        <div class="card-header">
            <i class="fa fa-align-justify"></i> Convocatorias
            @can('create announcements')
            <a class="btn btn-secondary" href="{{ route('admin.announcements.create') }}">
                <i class="icon-plus"></i>&nbsp;Nuevo
            </a>
            @endcan
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped table-sm">
                <thead>
                <tr>
                    <th>Titulo</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Fin</th>
                    <th>Fecha calificacion</th>
                    <th>Fecha calificacion fin</th>
                    <th>Opciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($announcements as $announcement)
                    <tr>
                        <td>{{ $announcement->title }}</td>
                        <td>{{ $announcement->start_date_announcement }}</td>
                        <td>{{ $announcement->end_date_announcement }}</td>
                        <td>{{ $announcement->start_date_calification }}</td>
                        <td>{{ $announcement->end_date_calification }}</td>
                        <td>
                            @can('edit announcements')
                            <a class="btn btn-warning btn-sm" href="{{ route('admin.announcements.edit', $announcement->id) }}">
                                <i class="icon-pencil"></i>
                            </a>
                            @endcan
                            @can('list requirements')
                            <a class="btn btn-success" href="{{ route('admin.requirements.index', $announcement->id) }}">
                                <i class="fa fa-edit"></i> Requerimientos
                            </a>
                                @endcan
                            @if(Auth::user()->hasRole(['Admin', 'Postulante']))
                                <a class="btn btn-outline-primary" href="{{ route('admin.requirements.files', $announcement->id) }}">
                                <i class="fa fa-upload"></i> subir
                            </a>
                                @endif
                                @if(Auth::user()->hasRole(['Calificador', 'Validador']))
                                    <a class="btn btn-outline-primary" href="{{ route('admin.postulants.index', $announcement->id) }}">
                                        <i class="fa fa-user"></i> Postulantes
                                    </a>
                                @endif
                                @can('edit announcements')
                            <a class="btn btn-info" href="#" onclick="show_code('{{ $announcement->code  }}');">
                                <i class="fa fa-lock"></i>
                            </a>
                                @endcan
                                @can('delete announcements')
                            <form action="{{ route('admin.announcements.destroy', $announcement->id) }}"
                                  style="display:inline-block;"
                                  method="POST">

                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <button type="button" class="btn btn-danger btn-sm"
                                        onclick="delete_action(event);">
                                    <i class="icon-trash"></i>
                                </button>
                            </form>
                            @endcan
                        </td>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        const show_code = (code) => {
            swalWithBootstrapButtons.fire({
                title: 'Que quieres realizar ?',
                text: "Cambiar el codigo no es recomendable!",
                icon: 'info',
                showCancelButton: true,
                confirmButtonText: 'Ver Codigo!',
                cancelButtonText: 'Cambiar, Codigo!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    showCode()
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    changePassword()
                }
            })

        }

        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-outline-success',
                cancelButton: 'btn btn-outline-danger'
            },
            buttonsStyling: false
        })

        const showCode = () => {
            return fetch(`{{ route('admin.announcements.show', [ 'id' => 1 ] ) }}`, {
                method: 'GET',
                //body: new URLSearchParams({code: text}),
                headers: new Headers({
                    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }),
            }).then(async response => {
                if (!response.ok) {
                    throw new Error(response.statusText)
                }

                let res = await response.json()

                swalWithBootstrapButtons.fire(
                    `Codigo => ${ res.code }`,
                    'Codigo para realizar postulacion.',
                    'success'
                )
            })
        }



        const changePassword = () => {
            Swal.fire({
                title: 'Cambiar codigo',
                html: `<h2 style='font-family: cursive'><strong>Ingrese el nuevo codigo</strong></2>.`,
                input: 'text',
                inputAttributes: {
                    autocapitalize: 'off'
                },
                showCancelButton: true,
                confirmButtonText: 'Cambiar',
                showLoaderOnConfirm: true,
                preConfirm: (text) => {
                    return fetch(`{{ route('admin.announcements.code', [ 'id' => 1 ] ) }}`, {
                        method: 'PUT',
                        body: new URLSearchParams({code: text}),
                        headers: new Headers({
                            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }),
                    }).then(response => {
                        if (!response.ok) {
                            throw new Error(response.statusText)
                        }
                        return response.json()
                    }).catch(error => {
                        if (error.message == 'Bad Request') {
                            Swal.showValidationMessage(
                                `El campo de texto no puede estar vacio.`
                            )
                        } else {
                            Swal.showValidationMessage(
                                `Request failed: ${error}`
                            )
                        }
                    });
                },
                allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                if (result.value) {
                    Swal.fire({
                        title: `Codigo cambiado con exito`,
                        imageUrl: 'https://fotos01.diarioinformacion.com/mmp/2018/11/18/690x278/inteligenciartificial.jpg'
                    })
                }
            })
        }

    </script>
@endsection